// <auto-generated />
namespace TtopAcademy.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OtherPracticeQuestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OtherPracticeQuestion));
        
        string IMigrationMetadata.Id
        {
            get { return "202206191320370_OtherPracticeQuestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
